baseURL = '/'
languageCode = 'en-us'
title = 'Reality Consultant'
theme = "hugo-blog-awesome"
enableEmoji = true

# Main menu
[[menu.main]]
  name = 'Posts'
  pageRef = 'posts'
  weight = 10

[[menu.main]]
  name = 'About'
  pageRef = 'about'
  weight = 20

# hugo.toml or config.toml

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[params.social]
  github = "yourusername"
  twitter = "yourusername"
  linkedin = "yourusername"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false

# Site parameters
[params]
  description = "Stepping into the future of systems thinking. Questioning the question to peel back from any silo trap."
  mainSections = ['posts']
  defaultColor = "dark" # dark, light, or auto
  [params.author]
    name = "The Reality Consultant"
    avatar = "avatar.jpg" # Make sure you have an avatar.jpg in your /assets/ folder
    description = "Your guide to understanding and navigating complex realities."
