# config.toml

# --- Basic Configuration ---
# Replace with your actual domain when you deploy
baseURL = "https://www.realityconsultant.com/"
languageCode = "en-us"
title = "Reality Consultant"
theme = "hugo-blog-awesome"
enableEmoji = true

# --- Main Navigation Menu (as per the blueprint) ---
[menu]
  [[menu.main]]
    name = "Frameworks"
    url = "/frameworks/"
    weight = 10
  [[menu.main]]
    name = "Analysis"
    url = "/analysis/"
    weight = 20
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30

# --- Site Parameters ---
[params]
  # Description for SEO and meta tags
  description = "A brutally honest and intellectually rigorous guide to the hidden systems that shape our lives. No Blame, Just Mapping."
  
  # Tells Hugo that the 'Analysis' section is the main blog feed for the homepage
  mainSections = ['analysis']
  
  # This theme setting is likely overridden by our custom CSS but is kept for completeness
  defaultColor = "dark"

  [params.author]
    name = "The Reality Consultant"
    # Ensure you have an avatar file at 'static/images/avatar.jpg'
    avatar = "images/avatar.jpg"
    description = "We are diagnosticians providing clarity."

  # Add your social media handles here if you want to display them
  # [params.social]
  #   Youtube = ""
  #   Email = "GeovanniGalan3@gmail.com"
  #   reddit = "TBD"

# --- Markdown Rendering Configuration ---
[markup]
  [markup.goldmark.renderer]
    # Set to true to allow raw HTML in your markdown content
    unsafe = true
  [markup.highlight]
    # This is required for Hugo's syntax highlighting to work
    noClasses = false